/* eslint-disable @typescript-eslint/no-explicit-any */
import {
  coy,
  coldarkDark,
  nightOwl,
  materialLight,
  materialDark,
  oneLight,
  oneDark,
  synthwave84,
  twilight,
  solarizedlight,
  coldarkCold,
  gruvboxDark,
  solarizedDarkAtom,
  prism,
  pojoaque,
  okaidia,
  nord,
  coyWithoutShadows,
} from "react-syntax-highlighter/dist/esm/styles/prism";

export const themes: Record<string, any> = {
  coldarkDark,
  okaidia,
  nightOwl,
  materialDark,
  gruvboxDark,
  pojoaque,
  materialLight,
  oneLight,
  oneDark,
  synthwave84,
  coy,
  nord,
  solarizedlight,
  coldarkCold,
  solarizedDarkAtom,
  prism,
  coyWithoutShadows,
  twilight,
};
